"""Regenerate cookbook/README.md from the recipe.json files.

Run it with --check in CI: the committed index must match what the metadata
produces, so there is no hand-maintained table of contents to drift.

    python cookbook/build_index.py          # rewrite README.md
    python cookbook/build_index.py --check   # fail if it would change
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).parent
INDEX = ROOT / "README.md"

TIERS = {
    "verified": "runs end to end in CI",
    "structural": "runs in CI with the agent stubbed; wiring checked, not judgement",
    "narrative": "a real recorded run; not executed in CI",
}

HEADER = """# The labloop cookbook

Worked examples: a real task, the real commands, and the run's real output —
including the trials that were thrown away, which are most of the information.

**This file is generated by `build_index.py`. Do not edit it by hand.**

Start with [Let Claude Code optimize real code](02-proposers/agent-optimizes-real-code/)
if you want to see what a loop actually looks like, and
[Four experiments, four noise levels](noise-across-recipes.md) for what they say
together. See [PROPOSAL.md](PROPOSAL.md) for what this is and
[CANDIDATES.md](CANDIDATES.md) for what is not built yet.

## Tiers

Every recipe declares how far it is verified, because the most useful ones
need a real agent or real hardware and cannot run in CI:

| Tier | Meaning |
| --- | --- |
"""


def recipes():
    for path in sorted(ROOT.glob("*/*/recipe.json")):
        yield path.parent, json.loads(path.read_text())


def render():
    out = [HEADER]
    for tier, meaning in TIERS.items():
        out.append(f"| `{tier}` | {meaning} |\n")

    by_section = {}
    for directory, meta in recipes():
        by_section.setdefault(meta.get("section", directory.parent.name), []).append(
            (directory, meta)
        )

    for section in sorted(by_section):
        out.append(f"\n## {section}\n\n")
        for directory, meta in sorted(by_section[section], key=lambda p: p[0].name):
            rel = directory.relative_to(ROOT)
            out.append(f"### [{meta['title']}]({rel}/)\n\n")
            out.append(f"*{meta['question']}*\n\n")
            out.append(f"`{meta['tier']}`")
            if meta.get("needs"):
                out.append(f" · needs {', '.join(f'`{n}`' for n in meta['needs'])}")
            out.append("\n")
            for line in meta.get("teaches", []):
                out.append(f"- {line}\n")
            out.append("\n")

    out.append("## Skills\n\n")
    out.append("Agent skills for the three moments a labloop user has an agent in the\n")
    out.append("room — see [skills/](skills/).\n\n")
    for skill in sorted((ROOT / "skills").glob("*/SKILL.md")):
        name = skill.parent.name
        out.append(f"- [`{name}`]({skill.relative_to(ROOT)})\n")
    return "".join(out)


def main():
    text = render()
    if "--check" in sys.argv:
        current = INDEX.read_text() if INDEX.exists() else ""
        if current != text:
            sys.exit("cookbook/README.md is stale; run `python cookbook/build_index.py`")
        print("cookbook index is current")
        return
    INDEX.write_text(text)
    print(f"wrote {INDEX} ({len(list(recipes()))} recipes)")


if __name__ == "__main__":
    main()
